/**
 * Sprint 10A-1.1 — Company ID Standardization Layer
 *
 * Problem: Different tables store company_id with different SQL types:
 *   - Most Drizzle-managed tables:    TEXT   (company_id = 'default')
 *   - customers (legacy Supabase):    INTEGER (company_id = 1)
 *   - Some tables:                    NULL   (no multi-tenancy yet)
 *
 * This module provides safe helpers so no route ever does a raw
 *   eq(table.companyId, 'default')
 * against a table with INTEGER company_id — which causes a Postgres
 * "invalid input syntax for type integer" runtime error.
 *
 * Usage:
 *   import { companyFilter, safeCompanyMatch } from "../lib/company-id";
 *   .where(and(companyFilter(aiTasksTable, companyId), ...))
 */

import { eq, sql } from "drizzle-orm";
import type { SQL } from "drizzle-orm";
import type { PgColumn, PgTable } from "drizzle-orm/pg-core";

/**
 * Tables whose company_id is INTEGER in the actual DB (schema drift).
 * For these tables, we must cast or use raw SQL to avoid type mismatch.
 */
const INTEGER_COMPANY_ID_TABLES = new Set<string>([
  "customers",
]);

/**
 * Tables where company_id is NULL for all rows (not yet multi-tenant).
 * Filtering on these would always return 0 rows — skip the WHERE clause.
 */
const NULL_COMPANY_ID_TABLES = new Set<string>([
  // none confirmed yet — add as discovered
]);

/**
 * Normalize a company ID string to its canonical form ("default" for
 * single-tenant deployments, or a UUID/slug for multi-tenant).
 */
export function normalizeCompanyId(raw: string | null | undefined): string {
  if (!raw || raw.trim() === "") return "default";
  return raw.trim().toLowerCase();
}

/**
 * Check if two company IDs refer to the same company, handling
 * format differences (string vs number, null vs "default", etc.).
 */
export function safeCompanyMatch(
  a: string | number | null | undefined,
  b: string | number | null | undefined,
): boolean {
  const na = String(a ?? "default").trim().toLowerCase();
  const nb = String(b ?? "default").trim().toLowerCase();
  return na === nb;
}

/**
 * Get the table name from a Drizzle table object.
 * Works for tables generated by pgTable(...).
 */
function getTableName(table: PgTable): string {
  // Drizzle stores the table name in a Symbol on the table object
  const sym = Object.getOwnPropertySymbols(table).find(
    (s) => s.toString().includes("drizzle:Name"),
  );
  if (sym) return (table as unknown as Record<symbol, string>)[sym] ?? "";
  return "";
}

/**
 * Build a Drizzle-safe WHERE condition for company_id filtering.
 *
 * For TEXT tables: uses Drizzle eq() — safe and typed.
 * For INTEGER tables: uses raw SQL cast to avoid type error.
 * For NULL tables: returns SQL `1=1` (no filter needed).
 *
 * @param table   — The Drizzle pgTable object
 * @param colRef  — The Drizzle column reference (table.companyId)
 * @param companyId — The company ID string (e.g. "default")
 */
export function companyFilter(
  table: PgTable,
  colRef: PgColumn,
  companyId: string,
): SQL {
  const tableName = getTableName(table);

  if (NULL_COMPANY_ID_TABLES.has(tableName)) {
    return sql`1=1`;
  }

  if (INTEGER_COMPANY_ID_TABLES.has(tableName)) {
    // company_id is INTEGER in DB but we pass "default" (string).
    // For single-tenant "default" context, return all rows (no filter).
    // For numeric company IDs, cast and compare.
    const asNum = parseInt(companyId, 10);
    if (isNaN(asNum)) {
      return sql`1=1`; // "default" → no integer equivalent, return all
    }
    return sql`${colRef} = ${asNum}`;
  }

  // Standard TEXT company_id — safe to use Drizzle eq()
  return eq(colRef, companyId) as unknown as SQL;
}

/**
 * Convenience: build companyFilter without needing the table object.
 * Use this when the table name is known statically.
 *
 * @param tableName  — Raw SQL table name string (e.g. "customers")
 * @param colRef     — Drizzle column reference
 * @param companyId  — Company ID string
 */
export function companyFilterByName(
  tableName: string,
  colRef: PgColumn,
  companyId: string,
): SQL {
  if (NULL_COMPANY_ID_TABLES.has(tableName)) {
    return sql`1=1`;
  }

  if (INTEGER_COMPANY_ID_TABLES.has(tableName)) {
    const asNum = parseInt(companyId, 10);
    if (isNaN(asNum)) return sql`1=1`;
    return sql`${colRef} = ${asNum}`;
  }

  return eq(colRef, companyId) as unknown as SQL;
}

/**
 * Raw SQL company_id filter — use when companyId column type is uncertain
 * or when using supabasePool raw queries. Always safe via CAST.
 *
 * Example: supabasePool.query(`SELECT * FROM customers WHERE ${rawCompanyFilter('customers', companyId)}`)
 */
export function rawCompanyFilter(tableName: string, companyId: string): string {
  if (INTEGER_COMPANY_ID_TABLES.has(tableName)) {
    const asNum = parseInt(companyId, 10);
    if (isNaN(asNum)) return "1=1"; // "default" = all customers
    return `company_id = ${asNum}`;
  }
  // TEXT: safe to embed (companyId is trusted internal value, never user input)
  return `company_id = '${companyId.replace(/'/g, "''")}'`;
}
